// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package partials

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"github.com/stackus/goht-todos/domain"
)

func EditTodoForm(todo domain.Todo) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<div class=\"block py-2 border-b-4 border-dotted border-red-900 draggable flex items-center\">\n<span class=\"handle\">\n<svg width=\"40\" height=\"40\" viewBox=\"0 0 40 40\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<rect x=\"10\" y=\"12\" width=\"20\" height=\"3\" fill=\"currentColor\"/>\n<rect x=\"10\" y=\"18.5\" width=\"20\" height=\"3\" fill=\"currentColor\"/>\n<rect x=\"10\" y=\"25\" width=\"20\" height=\"3\" fill=\"currentColor\"/>\n</svg>\n</span>\n<button class=\"mr-2 mt-2\" disabled>❌</button>\n<button class=\"mr-2 mt-2\" disabled>📝</button>\n<input type=\"hidden\" name=\"id\" value=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(todo.ID) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("><form class=\"inline\" method=\"POST\" action=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString("/todos/"+todo.ID+"/edit") + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" hx-target=\"closest div\" hx-swap=\"outerHTML\" hx-patch=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString("/todos/"+todo.ID) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">\n<input type=\"hidden\" name=\"completed\" value=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(goht.FormatString("%t", todo.Completed)) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("><input type=\"text\" name=\"description\" value=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(todo.Description) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("><input class=\"hidden\" type=\"submit\"></form>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
