// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package partials

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"github.com/stackus/goht-todos/domain"
)

func RenderTodos(todos []domain.Todo) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<form class=\"block p-0 mb-2 text-lg\" hx-post=\"/todos/sort\" hx-trigger=\"end\">\n<div id=\"todos\" class=\"sortable\">\n"); __err != nil {
			return
		}
		for _, todo := range todos {
			if __err = RenderTodo(todo).Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<div id=\"no-todos\" class=\"hidden first:block first:pb-2 first:pt-3\">\n<p>Congrats, you have no todos! Or... do you? 😰</p>\n</div>\n</div>\n</form>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
