// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package partials

import "context"
import "io"
import "github.com/stackus/goht"

func Search(term string) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<form class=\"inline [&:has(+ul:empty)]:hidden\" method=\"GET\" action=\"/todos\">\n<label class=\"flex items-center\">\n<span class=\"text-lg font-bold\">Search</span>\n<input id=\"search\" class=\"ml-2 grow\" name=\"search\" value=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(term) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" type=\"text\" placeholder=\"Begin typing to search...\" hx-get=\"/todos\" hx-target=\"#todos\" hx-trigger=\"keyup changed, search\" hx-replace=\"innerHTML\"></label>\n</form>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
