// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package pages

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"github.com/stackus/goht-todos/domain"
	"github.com/stackus/goht-todos/templates/partials"
	"github.com/stackus/goht-todos/templates/shared"
)

func HomePage(todos []domain.Todo) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		__var1 := goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
			__buf, __isBuf := __w.(goht.Buffer)
			if !__isBuf {
				__buf = goht.GetBuffer()
				defer goht.ReleaseBuffer(__buf)
			}
			if __err = partials.Search("").Render(ctx, __buf); __err != nil {
				return
			}
			if __err = partials.RenderTodos(todos).Render(ctx, __buf); __err != nil {
				return
			}
			if __err = partials.AddTodoForm().Render(ctx, __buf); __err != nil {
				return
			}
			if !__isBuf {
				_, __err = io.Copy(__w, __buf)
			}
			return
		})
		if __err = shared.Page("Home").Render(goht.PushChildren(ctx, __var1), __buf); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
