// Code generated by GoHT - DO NOT EDIT.
// https://github.com/stackus/goht

package shared

import "context"
import "io"
import "github.com/stackus/goht"

func Page(title string) goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!DOCTYPE html>\n<html class=\"h-full\" lang=\"en\">\n<head>\n<meta charset=\"UTF-8\"><title>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(title)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</title>\n<link rel=\"icon\" type=\"image/svg+xml\" href=\"/dist/favicon.svg\"><meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"><meta content=\"index, follow\" name=\"robots\"><meta content=\"7 days\" name=\"revisit-after\"><meta content=\"English\" name=\"language\"><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC\" crossorigin=\"anonymous\"></script>\n<script src=\"https://unpkg.com/hyperscript.org@0.9.12\"></script>\n<script src=\"https://unpkg.com/sortablejs@1.15.0\"></script>\n<script src=\"/dist/app.js\"></script>\n<link rel=\"stylesheet\" href=\"/dist/styles.css\"></head>\n<body class=\"h-full bg-yellow-50 font-mono\">\n<section class=\"max-w-lg mx-auto my-2\">\n<h1 class=\"text-8xl font-black text-center m-0 pb-2\">Todos</h1>\n"); __err != nil {
			return
		}
		if __err = __children.Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</section>\n</body>\n</html>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
